"""
Backend contract for SAT-SA's optional local explanation layer.

ARCHITECTURAL RULE (do not violate): a backend is handed a finding the
deterministic rule engine has ALREADY decided — finding_type, rule_id,
severity, rationale, evidence — and asked only to restate it in prose.
No backend may create, remove, or alter a finding, a severity, a risk
score, or a queue position. Nothing downstream reads a backend's output
as anything but display text.

Every backend must satisfy three properties, because the assessment
must complete on a machine where no model exists:

  1. `probe()` is fast and never raises. It answers "can I be used?"
     against a short timeout of its own, separate from generation.
     A supervisor gets "AI unavailable", never a frozen window.
  2. `explain()` never raises and never blocks past its timeout. It
     returns None on any failure; the caller keeps the deterministic
     rationale.
  3. Neither call is required for an assessment to succeed.
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional


#: The distinct states the UI must be able to show. Each one implies a
#: DIFFERENT next action for the operator, which is the whole reason
#: they are separate: someone who has never installed a runtime needs
#: different guidance from someone whose service is stopped, and both
#: differ from someone whose runtime is healthy but lacks the model.
#: Collapsing these into one "unavailable" state would leave a
#: supervisor with a red light and no idea what to do about it.
STATE_DISABLED = "disabled"
STATE_NOT_CONFIGURED = "not_configured"
STATE_NOT_INSTALLED = "not_installed"
STATE_NOT_RUNNING = "not_running"
STATE_MODEL_MISSING = "model_missing"
STATE_UNAVAILABLE = "unavailable"
STATE_AVAILABLE = "available"
STATE_MOCK = "mock"

#: Every state except AVAILABLE and MOCK means no model will run. The
#: deterministic assessment is unaffected in all of them.


@dataclass(frozen=True)
class BackendStatus:
    """The answer to 'is the local AI usable right now?'"""

    available: bool
    backend: str
    model: str = ""
    #: Supervisor-readable, shown verbatim in the UI status area.
    detail: str = ""
    #: True when this backend does not run a real language model.
    is_mock: bool = False
    #: One of the STATE_* constants above.
    state: str = ""

    def resolved_state(self) -> str:
        if self.state:
            return self.state
        if self.is_mock:
            return STATE_MOCK
        return STATE_AVAILABLE if self.available else STATE_UNAVAILABLE

    def headline(self) -> str:
        """Short form for a status tile."""
        return {
            STATE_DISABLED: "AI DISABLED",
            STATE_NOT_CONFIGURED: "AI NOT CONFIGURED",
            STATE_NOT_INSTALLED: "AI NOT INSTALLED",
            STATE_NOT_RUNNING: "AI NOT RUNNING",
            STATE_MODEL_MISSING: "AI MODEL MISSING",
            STATE_UNAVAILABLE: "AI UNAVAILABLE",
            STATE_MOCK: "SAMPLE EXPLANATIONS",
            STATE_AVAILABLE: "AI READY",
        }.get(self.resolved_state(), "AI UNAVAILABLE")

    def label(self) -> str:
        state = self.resolved_state()
        if state == STATE_MOCK:
            return f"SAMPLE EXPLANATIONS (no model) — {self.detail}"
        if state == STATE_AVAILABLE:
            return f"AI READY — {self.backend}: {self.model}"
        return f"{self.headline()} — {self.detail}"

    def remedy(self) -> str:
        """
        The one action that would move this state towards AI READY.

        Lives here rather than in the UI so every surface — settings
        page, status tile, report footer — gives the same instruction.
        """
        return {
            STATE_DISABLED: "Enable local AI explanations in Settings.",
            STATE_NOT_INSTALLED: (
                "Run SAT-SA-Setup-AI once to install the local AI runtime. "
                "SAT-SA works fully without it."),
            STATE_NOT_RUNNING: (
                "Start the Ollama service, then select Test AI. On Windows "
                "it normally starts with the machine."),
            STATE_MODEL_MISSING: (
                "Run SAT-SA-Setup-AI to add the model to the local runtime."),
            STATE_NOT_CONFIGURED: "Select a model file in Settings.",
        }.get(self.resolved_state(), "")


@dataclass(frozen=True)
class NarrationResult:
    """
    One explanation, plus the provenance needed to audit it.

    `is_mock` and `model` travel with the text all the way into the
    report and the UI. A sample explanation must never be presentable
    as the output of a language model that did not run — that would
    misrepresent the evidence base of a supervisory assessment.
    """

    text: str
    backend: str
    model: str
    is_mock: bool = False

    def provenance(self) -> str:
        if self.is_mock:
            return ("Generated by SAT-SA's built-in sample explainer "
                    "(deterministic template, no language model involved).")
        return f"Generated locally by {self.model} via {self.backend}."


PROMPT_TEMPLATE = """You are a supervisory-analytics assistant for SAT-SA, a tool that \
helps supervisors review how a Security Operations Centre handled its own alerts.

You are given ONE finding that a deterministic rule engine has already decided is \
real. Your only task is to restate it clearly for a human supervisor.

You MUST NOT: create findings, remove findings, change the severity, change any \
score, invent evidence, invent events, invent entities, or assert anything the \
supplied evidence does not state. If something is not in the evidence, say it is \
not available rather than inferring it.

finding_type: {finding_type}
rule_id: {rule_id}
severity: {severity}
entity: {soc_id}
rule_rationale: {rationale}
evidence: {evidence}

Write 2-3 sentences covering what was detected and why it matters to a supervisor, \
then one sentence naming a concrete next review step. Plain text only, no headings, \
no markdown, no bullet points."""


def build_prompt(finding: dict) -> str:
    """The single prompt every real backend uses, so they stay comparable."""
    return PROMPT_TEMPLATE.format(
        finding_type=finding.get("finding_type", "UNKNOWN"),
        rule_id=finding.get("rule_id", "UNKNOWN"),
        severity=finding.get("severity") or "N/A",
        soc_id=finding.get("soc_id", "N/A"),
        rationale=finding.get("rationale", ""),
        evidence=json.dumps(finding.get("evidence", {}), default=str, sort_keys=True),
    )


class LocalLLMBackend(ABC):
    """Base class for every local explanation backend."""

    name: str = "base"

    def __init__(self, config: Optional[dict] = None):
        self.config = config or {}
        self.model = self.config.get("model", "")
        self.temperature = float(self.config.get("temperature", 0.1))
        self.timeout = int(self.config.get("timeout_seconds", 120))
        # Availability must be answerable in about a second. Reusing the
        # generation timeout here would make a dead backend take minutes
        # to report itself dead, with the UI blocked behind it.
        self.probe_timeout = int(self.config.get("availability_timeout_seconds", 3))

    @abstractmethod
    def probe(self) -> BackendStatus:
        """Fast availability check. Must never raise."""

    @abstractmethod
    def explain(self, finding: dict) -> Optional[NarrationResult]:
        """Return an explanation, or None on any failure. Must never raise."""

    def close(self) -> None:
        """Release any held resource (model handle, session). Optional."""
